# Site settings
title: TenGames
email: tengames.inc@gmail.com
url: https://tengamesinc.github.io
description: "We make beloved nostalgic games for Android and iOS platforms."
keywords: "mobile, casual, puzzle, classic, nostalgic, game, game 2d, mobile game, casual game, online, online game"
skills: "we make beloved nostalgic games"
meta_author: Ten Games

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: tengames

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ten Games
  location: Location
  social: Around the Web
  credits: Agreements

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tengamesinc
  - title: facebook
    url: https://www.facebook.com/tengames.inc
  - title: github
    url: http://github.com/tengamesinc

# Postal address (add as many lines as necessary)
address:
  - line: Osaka, Japan
  - line: Osaka City, 530-0001

# Credits content
credits: 'We may collect your information to provide better Services. Please find below our <a href="terms-conditions.html">Terms and Conditions</a> and <a href="privacy-policy.html">Privacy Policy</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
